// <auto-generated />
namespace Dari.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class m62 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m62));
        
        string IMigrationMetadata.Id
        {
            get { return "202006041402279_m62"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
